# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for Stack

  target 'StackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StackUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Stack Widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for Stack Widget

end
